sudo: required
language: node_js
node_js: node

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t backpackerhh/docker-k8s-course-frontend .

script:
  - docker run -e CI=true backpackerhh/docker-k8s-course-frontend npm test
