sudo: required
language: node_js
node_js: node

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t backpackerhh/docker-k8s-course-frontend-dev .

script:
  - docker run -e CI=true backpackerhh/docker-k8s-course-frontend-dev npm test

before_deploy:
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  - docker build -t backpackerhh/docker-k8s-course-frontend .
  - docker tag backpackerhh/docker-k8s-course-frontend registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  edge: true
  provider: script
  script: docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: travis-heroku
