FROM node:16-alpine

WORKDIR /usr/app

RUN mkdir -p /usr/app/node_modules /usr/app/node_modules/.cache && \
  touch /usr/app/package-lock.json && \
  chown -R node:node /usr/app/node_modules /usr/app/node_modules/.cache /usr/app/package-lock.json

USER node

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "start"]
