version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
